project:
  type: website
  output-dir: docs

website:
  title: "Eco-Spatial Workshop"
  sidebar:
    style: docked
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "1 Setup"
        href: 01_setup.qmd
      - text: "2 Environmental features"
        href: 02_envFeatures.qmd
      - text: "3 Occurrence records"
        href: 03_occurrenceRecords.qmd
      - text: "4 Fitting a model"
        href: 04_modelFit.qmd
      - text: "5 Data visualization"
        href: 05_dataVis.qmd

format:
  html:
    theme: cosmos
    toc: true
